express_boilerplate:      # container name
  build: .                # build from the current directory
  ports:
    - "3300:3000"         # port forward 3000 from container to 3300 on host    
  environment: 
    ENV: Development      # set to Development environment
  volumes: 
    - ./:/app             # bind mount the app folder from the host
  links: 
    - redis_server        # link app to redis via redis_server:6379

redis_server:
  image: redis            # redis:3.2.4 to specify a version, else :latest